services:
  - type: web
    name: baka-ocr
    env: python
    region: singapore
    buildCommand: cd ocr && pip install -r requirements.txt
    startCommand: cd ocr && gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"

  - type: web
    name: baka-bot
    env: go
    region: singapore
    buildCommand: cd bot && go mod tidy && go build -o bot main.go
    startCommand: cd bot && ./bot
    plan: free
    envVars:
      - key: GO_VERSION
        value: "1.22"
      - key: BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: REPO_OWNER
        sync: false
      - key: REPO_NAME
        sync: false
      - key: ADMIN_ID
        value: "5376101564"
      - key: CONCURRENCY
        value: "100"
      - key: WEB_PORT
        value: "8080"
      - key: OCR_SERVER
        value: "https://baka-ocr.onrender.com"